[project]
name = "pydsa"
description = "dsa"
readme = "readme.md"
version = "0.1.0"
requires-python = ">=3.13"
dependencies = []

[dependency-groups]
dev = [
    "jupyter>=1.1.1",
    "jupyter-book>=2.1.0",
]
